# Common
setopt AUTOCD
setopt NOBEEP
setopt NUMERIC_GLOB_SORT

# History
HISTFILE="$XDG_STATE_HOME/zsh_history"
HISTSIZE=100000
SAVEHIST=100000

setopt APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_FIND_NO_DUPS

# ZVM
ZVM_LINE_INIT_MODE="$ZVM_MODE_NORMAL"
ZVM_INSERT_MODE_CURSOR="$ZVM_CURSOR_BEAM"
ZVM_NORMAL_MODE_CURSOR="$ZVM_CURSOR_BLOCK"
ZVM_VISUAL_MODE_CURSOR="$ZVM_CURSOR_BLOCK"
